name: Build Theos Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git curl wget perl clang make dpkg

      - name: Install ldid (from source)
        run: |
          git clone https://github.com/tpoechtrager/ldid.git
          cd ldid
          git submodule update --init
          make
          sudo cp ldid /usr/local/bin/

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo 'export THEOS=$HOME/theos' >> $HOME/.bashrc
          echo 'export PATH=$THEOS/bin:$PATH' >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Build the package
        run: |
          make package

      - name: Upload the package
        uses: actions/upload-artifact@v4
        with:
          name: tweak-package
          path: ./packages/*.deb
